### ISSUE TITLE
Add synchronisation feature

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/hexo-algoliasearch#1]
- [x] Create an hook to add an `algolia_object_id` variable to a new post. (on `hexo new post "post-title"`).
- [x] Create a command to add `algolia_object_id` variable to all posts (`hexo algolia -i` or `hexo algolia --init`)
- [ ] Create a command to index post manually (sync)
- [ ] Create an hook to sync post before deploy. (sync on `deployBefore` event)

**Comment by LouisBarranqueiro** [comment]
Waiting responses on these issues to deliver this feature: 
- https://github.com/hexojs/hexo/issues/2045
- https://github.com/hexojs/hexo/issues/2049

**Comment by caynan** [comment]
@LouisBarranqueiro do you mind claryfing what you mean by "Create a command to index post manually(sync)" you want to give the user the option to index a specific post instead of all posts?

**Comment by LouisBarranqueiro** [comment]
No, just a command to all posts manually otherwise the sync is started before deploy

**Comment by caynan** [comment]
I'm sorry, I still don't get it. What is the objective of that feature?

**Comment by LouisBarranqueiro** [comment]
Synchronisation : only index updated posts, added posts and deleted posts. 
Currently, it index all posts each time the blog is deployed.
