### ISSUE TITLE
hexo algolia search cannot pop up

### ISSUE THREAD

**Issue by stevechoris** [LouisBarranqueiro/hexo-algoliasearch#10]
I registed an algolia account and configured it as [README.MD](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak) suggested. But when i click search on the dock of my blog, it didn't pop up. why?

**Comment by LouisBarranqueiro** [comment]
Hey @stevechoris, could you open console and copy & paste error message here, if there is one?

**Comment by stevechoris** [comment]
Sorry, it is not the issue of this plugin. It’s because i used an old version of hexo-theme-tranquilpeak <https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md>. After i updated it to the latest version and it worked. Thank you very much.

**Comment by LouisBarranqueiro** [comment]
Good news :)
