### ISSUE TITLE
AlgoliaSearchRequestTimeoutError: Request timedout before getting a response

### ISSUE THREAD

**Issue by kianlai** [LouisBarranqueiro/hexo-algoliasearch#12]
I copy the configuration in my `_config.yml` file,  run `hexo algolia -n`, then tell me timeout, what could I do ? Does it mean I should create a new algolia account ?

## Error Behavior
[root@localhost hexo]# hexo algolia -n
(node:10432) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Collecting posts...
INFO  Start processing
INFO  Files loaded in 5.28 s
INFO  Generated: atom.xml
INFO  Generated: all-archives/index.html
INFO  Generated: all-categories/index.html
INFO  Generated: all-tags/index.html
INFO  Generated: 2017/07/02/hello-world/index.html
INFO  Generated: 2017/07/02/ABAP-Performance-Analysis/index.html
INFO  Generated: 2017/07/02/Getting-Git-on-CentOS7-Server/index.html
INFO  Generated: 2017/07/02/Using-Jekyll/index.html
INFO  Generated: 2017/07/02/Install-Hexo-on-CentOS-7/index.html
INFO  Generated: 2017/07/02/Learn-Python/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2017/index.html
INFO  Generated: archives/2017/07/index.html
INFO  Generated: index.html
INFO  Generated: tags/jekyll/index.html
INFO  Generated: tags/centos/index.html
INFO  Generated: tags/git/index.html
INFO  Generated: tags/sap/index.html
INFO  Generated: tags/abap/index.html
INFO  Generated: tags/hexo/index.html
INFO  Generated: tags/key/index.html
INFO  Generated: tags/performance/index.html
INFO  Generated: tags/python/index.html
INFO  Generated: tags/learn/index.html
INFO  Generated: tags/blog/index.html
INFO  25 files generated in 1.3 s
INFO  5 posts collected
INFO  Indexing posts on Algolia...
INFO  Error has occurred during indexing posts : AlgoliaSearchRequestTimeoutError: Request timedout before getting a response

/home/kian/hexo/node_modules/hexo-algoliasearch/lib/algolia.js:92
        throw err;
        ^
Error
    at Timeout.timeout [as _onTimeout] (/home/kian/hexo/node_modules/hexo-algoliasearch/node_modules/algoliasearch/src/server/builds/node.js:234:14)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

**Comment by aerohub** [comment]
@kianlai, you must have your own account on https://algolia.com/ and fill the config algolia credentials
