### ISSUE TITLE
ignore hidden post

### ISSUE THREAD

**Issue by soxft** [LouisBarranqueiro/hexo-algoliasearch#135]
### Description
When setting a parameter to an article, do not index this article

### Explanation / motivation
Some articles are hidden by plugins, is there any way to prevent them to be indexed

### Additional information
- [ ] I can implement this feature / improvement

**Comment by LouisBarranqueiro** [comment]
👋 @soxft , I'm sorry I don't understand the feature. What's the use case for it?

**Comment by soxft** [comment]
> 👋 @soxft , I'm sorry I don't understand the feature. Index where? What's the use case for it?

I mean, some posts may be hidden using hexo-hide-posts so that they don't appear in the post list, but are still directly accessible via the link.  Sometimes we may not want algolia to index them
