### ISSUE TITLE
Why does it say `0 posts collected`?

### ISSUE THREAD

**Issue by ParkYoungWoong** [LouisBarranqueiro/hexo-algoliasearch#15]
Hi, LouisBarranqueiro.
I like your hexo plugin.
However, when I run `hexo algolia`, it says `0 posts collected` on the console.
I don't know why.
Do you have any guesses?

PS, push to Algolia Index works well.
`Indexation done. 0 posts indexed.`

**Comment by ParkYoungWoong** [comment]
I tried `hexo clean`, but it still does not work.
Below is my hexo version.
```
hexo: 3.4.4
hexo-cli: 1.0.4
```

**Comment by ParkYoungWoong** [comment]
I solved this problem.
The `plugins` setting in the `_config.yml` file conflicts with other plugins.
So, removed `hexo-algoliasearch` from `plugins` and Hexo will automatically detect it and works well.
Thanks to good plugin.

**Comment by LouisBarranqueiro** [comment]
👋 @ParkYoungWoong , Sorry for the late response. So Hexo automatically detects `hexo-algoliasearch` plugin?
