### ISSUE TITLE
Default install is behind @ 3.24.6

### ISSUE THREAD

**Issue by ILAsoft** [LouisBarranqueiro/hexo-algoliasearch#16]
When running the standard install (npm install hexo-algoliasearch --save), I get a warning:
npm WARN deprecated algoliasearch@3.24.6: This version has an error in the implementation of copyIndex without any options. Please use 3.24.7
+ hexo-algoliasearch@0.2.3

When checking npmjs, it does report 3.24.6 as the one currently published.

**Comment by LouisBarranqueiro** [comment]
👋 @ILAsoft , I'll update `algoliasearch` version

**Comment by LouisBarranqueiro** [comment]
Done. Latest `hexo-algoliasearch` version uses `algoliasearch@3.24.7`
