### ISSUE TITLE
Add flag to truncate some fields

### ISSUE THREAD

**Issue by shyim** [LouisBarranqueiro/hexo-algoliasearch#17]
Hey thanks for that extension ❤️ ,
i am currently trying to index also the content to algolia. It works, but on one page algolia throws a error that the body is to large.  A config option to truncate some fields were cool, to avoid that problem.

**Comment by LouisBarranqueiro** [comment]
👋 shyim, good idea, I'm on it.

**Comment by LouisBarranqueiro** [comment]
👋 Get the new version and use truncate filter like this:
``` yml
- content:strip:truncate,0,300
```
See more [here](https://github.com/LouisBarranqueiro/hexo-algoliasearch#filters)
