### ISSUE TITLE
Search returning undefined

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-algoliasearch#21]
My pulgin settings:
![search_undefined](https://user-images.githubusercontent.com/33632286/50704345-a97a3d00-101c-11e9-8e02-dc47e68eecbc.jpg)

The result of my algolia indexing:
![algolia](https://user-images.githubusercontent.com/33632286/50704346-aa12d380-101c-11e9-82fc-118d3b6d6242.jpg)

Any idea why undefined is popping up? Having trouble debuging cause i'm not sure of it's intended behavior.

Thanks
Ben

**Comment by aerohub** [comment]
@bmitchinson,
it looks like you have not configured your search app using Configuration tab in Algolia dashboard

![1](https://user-images.githubusercontent.com/16353578/52177682-c483cc80-27d5-11e9-8bce-e78c8100873c.png)

**Comment by bmitchinson** [comment]
@aerohub thank you so much, yeah I just completely failed to do that.

..... seems to be a lot of options for configuration, any good resources for a simple setup? Maybe setups used within the context of Tranquilpeak ?

**Comment by aerohub** [comment]
@bmitchinson You are right, there are really a lot of options. I think that there is no universal recipe, because every website owner has his own vision, own goals and tasks that he wants to solve with site search engine. In any case, no one bothers you to experiment with the settings

**Comment by LouisBarranqueiro** [comment]
👋 @bmitchinson, sorry for the late response. Did you manage to set up the search? 

Thanks, @aerohub  for the help 👍

**Comment by bmitchinson** [comment]
@LouisBarranqueiro I never got it working 🤔 

I have this in my configuration, and a populated index as shown in my initial image:

![image](https://user-images.githubusercontent.com/33632286/54166998-c7598900-4435-11e9-8d68-de6d35f323b6.png)


 which I assumed would correct the site, but still getting the image originally above :(

**Comment by LouisBarranqueiro** [comment]
I see. You need to index the `thumbnailImageUrl`. I just noticed the required fields are not specified in the documentation of the theme. I'm gonna take care of that.
Here is the fields you need:
``` yaml
  fields:
    - title
    - tags
    - date
    - categories
    - excerpt
    - excerpt:strip
    - content:strip:truncate,0,50
    - permalink
    - thumbnailImageUrl
```

**Comment by bmitchinson** [comment]
Please consider reopening this issue @LouisBarranqueiro 

I changed my fields to match exactly what you listed, thank you for taking the time to help me learn what to set them as, however, I still get the same issue. Attached is a video of the problem.

[![Search Issue](https://i.imgur.com/niU5SB9.png0)](https://youtu.be/bwhj0Jcsd5c "Search Issue")

You'll notice that all of the search results are fine upon loading the search menu initially, but they all list as "undefined" once I hit return with no input text. The intent of the search, I assume, is that pressing return wouldn't change any of the results.

Additionally, when I do a search for a term that's written within a post, the searching works correctly, because "Chladni Figures" returns the post called "Lazerphonic" (the post that does mention the "Chladni Figures" term). It's just that the post "Lazerphonic" has no description, only undefined.

This is what originally led me to believe it was something within the theme, and not an Algolia preference, but not entirely sure.

(Additionally, the logo in the upper right is no longer hosted at "https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg" )
![image](https://user-images.githubusercontent.com/33632286/54221751-1c42e100-44c2-11e9-9b07-4d36aa1055c0.png)

**Comment by LouisBarranqueiro** [comment]
@bmitchinson yes, that's weird, please open an issue in the repo of the theme since it's not related to this module. Also could you please include the HTML code of the model once the searched something. It would be even better if I could test it live so I can debug it :)
