### ISSUE TITLE
Thanks for the plugin

### ISSUE THREAD

**Issue by pixelastic** [LouisBarranqueiro/hexo-algoliasearch#3]
Hello,

First of all, sorry to contact you through the GitHub issues but that's the only way to that I could find. 

Thanks you for all the time and skills you put into creating this Algolia/Hexo plugin. I work at Algolia, and I love seeing the community building stuff using our engine. Feel free to contact me at tim at algolia dot com so I can send you a thank you gift :)

**Comment by LouisBarranqueiro** [comment]
Hey @pixelastic, thanks for the message. I really appreciate :grinning: I talked to you on [Gitter](https://gitter.im/LouisBarranqueiro).
