### ISSUE TITLE
Seems like installing plugin disables builtin hexo server

### ISSUE THREAD

**Issue by dyashkir** [LouisBarranqueiro/hexo-algoliasearch#6]
Reading hexo documentation it seems that server was moved into a separate plugin, however it does work without installing. With search installed it seems to break this. However installing the server plugin fixes the issue.

edit

Actually never mind, the installed server while it runs does not serve anything. Uninstalling the algo plugin fixes it. Probably hexo version issue, I am using 3.2.2

**Comment by LouisBarranqueiro** [comment]
Hey @dyashkir, I don't really understand the issue, but yeah, `hexo-server` plugin is responsible to serve files during writing/development phase. 

Is it working?

**Comment by PeoceWang** [comment]
I also find that when I add following line to my _config.yml and run " hexo algolia"

> plugins:
>   - hexo-algoliasearch


I CAN NOT RUN "hexo s" to preview  my blog in localhost ???!!!

**Comment by LouisBarranqueiro** [comment]
@PeoceWang 
try:
``` yml
plugins:
  -hexo-footnotes
```

open an issue if it does not work

**Comment by PeoceWang** [comment]
@LouisBarranqueiro It works !  tks a lot
