### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by unicornt** [LouisBarranqueiro/hexo-algoliasearch#9]
when I clicked "search",nothing happened.

**Comment by LouisBarranqueiro** [comment]
Hey @unicornt, Did you read the README? It seems that you misunderstood the goal of this plugin.
> A plugin to index posts of your Hexo blog on Algolia

**Comment by unicornt** [comment]
can you tell me how to search?
sorry for my poor english

**Comment by LouisBarranqueiro** [comment]
As I said, this plugin does not provide search feature. it index your hexo blog posts. If you wanna search, use [Algolia search API](https://github.com/algolia/algoliasearch-client-js

**Comment by unicornt** [comment]
Thank you!

**Comment by LouisBarranqueiro** [comment]
What are you trying to do? which theme do you use?

**Comment by unicornt** [comment]
tranquilpeak

**Comment by unicornt** [comment]
can you add this function to that theme?

**Comment by LouisBarranqueiro** [comment]
It is already integrated, read [tranquilpeak user doc - Algolia integration](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#algolia)

**Comment by unicornt** [comment]
yes,I read that doc.But I don't know how to "Configure the search on your Algolia dashboard",need I add my website to dashboard?

**Comment by LouisBarranqueiro** [comment]
no, just go on your Algolia account -> your indice -> and configure the search results (ranking) but it's optional

**Comment by unicornt** [comment]
I config like this,is that right?
search:
            title: Search
            url: /#search
            icon: search
            class: open-algolia-search

**Comment by unicornt** [comment]
thank you for your patience

**Comment by unicornt** [comment]
but I really have trouble

**Comment by LouisBarranqueiro** [comment]
yeah, did you add your algolia config (API key, secret, etc..) in main configuration file? `_config.yml`

**Comment by unicornt** [comment]
yes,like this:
plugin: hexo-algoliasearch
algolia:
  appId: "BYW2FU7XP8"
  apiKey: "d4e0895980fa9c2e4a4f42027d942a2f"
  adminApiKey: "cdf590870565b6076452109bd2c83cef"
  chunkSize: 5000
  indexName: root
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip

**Comment by unicornt** [comment]
I have solved this problem.
I use 1.8.0 instead of 1.9.1.
sorry ...

**Comment by LouisBarranqueiro** [comment]
np man. good news :)
